name: base random nodejs pipeline

on:
  workflow_dispatch:

jobs:
  versioned-container-image:
    name: build versioned container image
    uses: nmbrs/reusable-workflows/.github/workflows/container-image.workflow.yaml@feature/add-docker-workflow
    with:
      container_image_tag: '1.0.0'

  image-name-output:
    runs-on: ubuntu-latest
    needs: versioned-container-image
    steps:
      - name: echo image full name
        run: echo ${{needs.versioned-container-image.outputs.container_image_name}}

  latest-container-image:
    name: build latest container image
    needs: versioned-container-image
    uses: nmbrs/reusable-workflows/.github/workflows/container-image.workflow.yaml@feature/add-docker-workflow
